/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import reactor.core.publisher.Flux;
import reactor.core.scheduler.Schedulers;

public class LibraryTest {

    @Test
    public void asyncStackTraceDebugger() {
        final Flux<Integer> range = Flux.range(1, 2).hide();

        range.publishOn(Schedulers.parallel())
             .map(v -> v + 2)
             .subscribe(v -> System.out.println(v + "")); //breakpoint in this lambda or in lambda above
    }
}
