/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.time.Duration;

import org.junit.Test;
import reactor.core.publisher.Flux;
import reactor.core.scheduler.Schedulers;

public class PublishOnTest {

    @Test
    public void asyncStackTraceDebugger() throws InterruptedException {
        final Flux<Integer> range = Flux.range(1, 2).hide();

        range
                .map(v -> v - 3)
                .delayElements(Duration.ofSeconds(1))
                .publishOn(Schedulers.parallel())
                .map(v -> v + 2)
                .subscribe(v -> System.out.println(v + "")); //breakpoint in this lambda or in lambda above

	    Thread.sleep(3000);
    }
}
