/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import reactor.core.publisher.*;
import reactor.core.scheduler.Schedulers;

public class PublishOnTest {

    @BeforeAll
    private static void debugModeOn() {
        Hooks.onOperatorDebug();
    }

    @AfterAll
    private static void debugModeOff() {
        Hooks.resetOnOperatorDebug();
    }

    @Test
    public void asyncStackTraceDebugger() throws InterruptedException {
        final Flux<Integer> range = Flux.range(1, 2).hide();

        range
                .map(v -> v - 3)
                .publishOn(Schedulers.parallel())
                .map(v -> v + 2)
                .subscribe(v -> System.out.println(v + "")); //breakpoint in this lambda or in lambda above

        Thread.sleep(3000);
    }
}
